    executable   = ../updown_network.py 
     universe     = vanilla  
    request_gpus = 1 
    request_memory = 16GB 
    requirements = TARGET.CUDACapability 
    log          = train_hist/2017-09-09/time_l0_v2_time-1/condor.log 
    output       = train_hist/2017-09-09/time_l0_v2_time-1/condor.out 
    error        = train_hist/2017-09-09/time_l0_v2_time-1/condor.err 
    getenv = True 
     stream_output = True 
    IWD = /data/user/jkager/NN_Reco/johannes/updownclassification_3/ 
    arguments =  --project time_l0_v2_time-1 --continue None --model=CNN_2.cfg --input=l0 --using=time --date 2017-09-09 
    queue 1 
    